Se extrae comportamiento de SignIn y SignUp
unq-arqsoft-difi/covid-front-react pull request #6
Opened 2020-06-06 05:55 UTC by fischettij

2020-06-06 05:56 UTC, fischettij commented
#5

2020-06-06 15:51 UTC, laendoor requested changes
Se piden algunas mejoras

2020-06-06 15:51 UTC, leandrojdl commented on .env.example
> +BASE_URL=http://localhost:9004
No te sirven los .env en un front de estas características. Cuando se buildea se generan todos .js que corren en el browser del client. No tenés un environment de donde sacar info.

Usá un archivo de configuración, puede ser un js, yaml, json, lo que preferieras.

El archivo de configuración para prod puede no quedar trackeado y se escribe directamente en el server de prod.

2020-06-06 15:51 UTC, leandrojdl commented on src/components/SignIn.jsx
> +    authenticateWith(data).then(history.push("/")).catch(setRequestStatus({ status: 'error' }))
Mi TOC pregunta si podés poner cada sentencia una abajo de la otra :grin: 

```js
authenticateWith(data)
  .then(history.push("/"))
  .catch(setRequestStatus({ status: 'error' }))
```

2020-06-06 15:51 UTC, leandrojdl commented on src/components/SignUp.jsx
> +      .then(() => {console.log("HOLAA"); history.push("/login")})
volá el console.log

2020-06-06 15:51 UTC, leandrojdl commented on src/components/SignIn.jsx
> +    authenticateWith(data).then(history.push("/")).catch(setRequestStatus({ status: 'error' }))
esos `then` y `catch` funcionan? así como están puestos los va a querer evaluar como funciones: `history.push("/")()`

Lo que deberías hacer es `.then(() => history.push("/"))`

2020-06-06 15:51 UTC, leandrojdl commented on src/components/SignUp.jsx
> +        console.log(body);
ídem

2020-06-06 15:51 UTC, leandrojdl commented on src/contexts/AuthContext.jsx
> +    console.log(authInfo.token)
vuela

2020-06-06 15:51 UTC, leandrojdl commented on src/services/AuthService.js
> +          if (error.response) { reject(error.response.data) }
Si no hay `error.response` no hacés `reject`?

2020-06-06 15:51 UTC, leandrojdl commented on src/services/UsersService.js
> +          if (error.response) { reject(error.response.data) }
ídem anterior

2020-06-06 15:51 UTC, leandrojdl commented on src/services/http-common.js
> +  baseURL: 'http://localhost:9001/',
Ahora que estamos en etapa de deploy esto tiene que ser configurable

2020-06-06 20:05 UTC, fischettij commented on .env.example
> +BASE_URL=http://localhost:9004
Iba a usar babel pero esto es mejor, lo cambio

2020-06-06 20:18 UTC, fischettij commented on src/components/SignUp.jsx
> +      .then(() => {console.log("HOLAA"); history.push("/login")})
hay que meter un hook que revise eso

2020-06-06 20:21 UTC, fischettij commented on src/components/SignIn.jsx
> +    authenticateWith(data).then(history.push("/")).catch(setRequestStatus({ status: 'error' }))
listo

2020-06-06 20:21 UTC, fischettij commented on .env.example
> +BASE_URL=http://localhost:9004
meti un json de config

2020-06-06 20:22 UTC, fischettij commented on src/components/SignIn.jsx
> +    authenticateWith(data).then(history.push("/")).catch(setRequestStatus({ status: 'error' }))
estaban mal escritos, listo

2020-06-06 20:22 UTC, fischettij commented on src/components/SignUp.jsx
> +        console.log(body);
listo

2020-06-06 20:23 UTC, fischettij commented on src/contexts/AuthContext.jsx
> +    console.log(authInfo.token)
listo

2020-06-06 20:26 UTC, fischettij commented on src/services/AuthService.js
> +          if (error.response) { reject(error.response.data) }
de momento no

2020-06-06 20:26 UTC, fischettij commented on src/services/AuthService.js
> +          if (error.response) { reject(error.response.data) }
se puede cambiar despues

2020-06-06 20:26 UTC, fischettij commented on src/services/http-common.js
> +  baseURL: 'http://localhost:9001/',
ya se, por eso habia puesto el .env y pensaba levantarlo con babel

2020-06-07 00:58 UTC, laendoor approved these changes

2020-06-07 01:03 UTC, merged